name: CI
on:
  push:
    branches:
      - php
  pull_request:
    branches:
      - php

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: prepare
        uses: docker://ecoding/php:8.0
        with:
          args: composer install

      - name: test
        uses: docker://ecoding/php:8.0
        env:
          XDEBUG_MODE: coverage
        with:
          args: ./vendor/bin/pest --coverage-clover coverage.xml

      - name: codecov
        uses: codecov/codecov-action@v1

      - name: GitHub Environment Variables Action
        uses: FranzDiebold/github-env-vars-action@v2

      - name: debug
        run: |
          echo "CI_ACTION_REF_NAME=$CI_ACTION_REF_NAME"
          echo "CI_ACTION_REF_NAME=${CI_ACTION_REF_NAME}"
          echo "CI_ACTION_REF_NAME=${{ CI_ACTION_REF_NAME }}"

      - name: build
        uses: docker://ecoding/php:8.0
        env:
          CI_SHA_SHORT: ${{ CI_SHA_SHORT }}
        with:
          args: php coding app:build --build-version=${{ env.CI_SHA_SHORT }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: coding
          path: builds/coding

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        env:
          CI_ACTION_REF_NAME: ${{ CI_ACTION_REF_NAME }}
        with:
          push: true
          context: .
          tags: ecoding/coding-cli:latest,ecoding/coding-cli:${{ env.CI_ACTION_REF_NAME }}

      - name: Image digest
        if: steps.docker_build.conclusion == 'success'
        run: echo ${{ steps.docker_build.outputs.digest }}
